version: '2'

services:
    httpd:
        image: abiosoft/caddy:php
        env_file: .env
        environment:
            - PHP_FPM_ADDR=172.16.${IP_RANGE}.12
            - PHP_FPM_PORT=9000

        ports:
            - "127.0.0.1:80:80"
            - "127.0.0.1:443:443"

        networks:
            dev_net:
                ipv4_address: 172.16.${IP_RANGE}.11

        volumes:
            - ./Caddyfile:/etc/Caddyfile
            - ./srv:/srv

        links:
            - "php:php"


    php:
        image: cytopia/php-fpm-7.0
        env_file: .env
        environment:
            - TIMEZONE=Europe/London
            - ENABLE_MAIL=0

        ports:
            - "127.0.0.1:9000:9000"

        networks:
              dev_net:
                ipv4_address: 172.16.${IP_RANGE}.12

        volumes:
            - ./Caddyfile:/etc/Caddyfile
            - ./srv:/srv
            - ./logs/mail:/var/mail
            - ./logs/php:/var/log/php-fpm
            - ./config:/etc/php-custom.d


networks:
  dev_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.${IP_RANGE}.0/25
        gateway: 172.16.${IP_RANGE}.1
